config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  root 'users#new'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :integer          not null, primary key
#  name                     :string
#  mail                     :string
#  password_digest          :string           not null
#  encrypted_remember_token :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :mail, uniqueness: true, presence: true
  validates :encrypted_remember_token, uniqueness: true
  before_create :save_new_remember_token

  class << self
    def create_remember_token
      SecureRandom.urlsafe_base64
    end

    def encrypt(token)
      Digest::SHA256.hexdigest(token.to_s)
    end
  end

  private
  def save_new_remember_token
    self.encrypted_remember_token = User.encrypt(User.create_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  protect_from_forgery with: :exception

  def authenticate_user
    unless signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :hide_from_signed_in_user, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(mail: params[:session][:mail])
    if user.present? and user.authenticate(params[:session][:password]) and sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'メールアドレス、もしくはパスワードが間違っています。'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def hide_from_signed_in_user
    if signed_in?
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_to profile_path, notice: 'ユーザの新規登録に成功しました。'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to profile_path, notice: 'ユーザ情報の更新に成功しました。'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'ユーザは削除されました。'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(
        :name,
        :mail,
        :password,
        :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.create_remember_token
    session[:remember_token] = remember_token
    user.encrypted_remember_token = User.encrypt(remember_token)
    user.save
  end

  def current_user
    @current_user ||= User.find_by(encrypted_remember_token: User.encrypt(session[:remember_token]))
  end

  def signed_in?
    current_user.present?
  end

  def sign_out
    current_user.encrypted_remember_token = nil
    session.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
html
  head
    title てづくり認証
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .row
      .col-xs-4.col-xs-offset-4
        h1.text-center てづくり認証
    .row
      .col-xs-4.col-xs-offset-4
        == yield
    .row
      .col-xs-4.col-xs-offset-4
        - if signed_in?
          .list-group
            = link_to '#', class: 'list-group-item'
              span.glyphicon.glyphicon-info-sign ログイン中です
            = link_to '#', class: 'list-group-item'
              span.glyphicon.glyphicon-user #{current_user.name}
            = link_to profile_edit_path, class: 'list-group-item'
              span.glyphicon.glyphicon-pencil 個人情報編集
            = link_to root_path, class: 'list-group-item'
              span.glyphicon.glyphicon-home トップページへ
            = link_to signout_path, method: :delete, class: 'list-group-item'
              span.glyphicon.glyphicon-log-out ログアウト

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} ユーザ情報の保存に失敗しました:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :mail
    = f.text_field :mail, class: 'form-control'
  .field
    = f.label :password
    = f.password_field :password, class: 'form-control'
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'
  .actions = f.submit value: '送信', class: 'btn btn-primary'

app/views/users/edit.html.slim
h2.text-center 個人情報編集

== render 'form'

app/views/users/new.html.slim
-if signed_in?
  h2.text-center ようこそ
-else
  h2.text-center 新規登録
  == render 'form'
  = link_to 'すでに登録済みの場合はこちらからログイン', signin_path

app/views/users/show.html.slim
h2.text-center 個人情報確認
p#notice = notice

table.table
  tbody
    tr
      th 名前
      td = @user.name
    tr
      th メールアドレス
      td = @user.mail